### PR TITLE
README: Formatting / indentation

### PR DESCRIPTION
**Pull request by tony**
Just stuff found while reading docs, thank you for the project!

### CODE REVIEW

**Comment by morrys** [comment]
Hi @tony,
thank you for your contribution.

Could you check this file too?
https://github.com/relay-tools/relay-hooks/blob/master/docs/RelayHooks-Introduction.md

In a future release I will remove the github documentation in favor of the docusaurus generated documentation:
https://relay-tools.github.io/relay-hooks/docs/relay-hooks#relay-hooks

**Comment by tony** [comment]
@morrys Checking

**Comment by tony** [comment]
@morrys see #120  (I don't have this checked out via CLI, I'm editing via gh editor at the moment)

**Comment by tony** [comment]
@morrys Better now? (Between #119 and #120?)

**Comment by morrys** [comment]
yes :)

Contributions to the documentation are always welcome :)

**Comment by tony** [comment]
@morrys Thank you!

**Pull request merged**
