### PR TITLE
[proposal] Added onResponse callback in the hooks

### PR DESCRIPTION
**Pull request by morrys**
Proposed for the resolution of issue https://github.com/relay-tools/relay-hooks/issues/176

Added the onResponse callback parameter to intercept the server response when a successful network call is made via hooks (query, refetch, pagination)

This minimizes the difference in behavior from official relay and leaves users free to manage the response as they want. 

I'd like your opinion @aleksandrlat, @n1ru4l, @sibelius

### CODE REVIEW

**Comment by morrys** [comment]
Although I am still of the idea described in this comment #176 (comment), I find the observation of @aleksandrlat right, relay allows rendering the query even in the presence of errors so it is right to give a chance to intercept them.

**Comment by aleksandrlat** [comment]
Thank you @morrys so much!

I personally think it is fine to return data and error from useQuery hook because this is what happens.
And we already have both data and error in useQuery API.

Let's compare 2 examples:
onResponse
```
let responseError = null
const onResponse = (response) => {
  responseError = response.error
}
const { data, error } = useQuery(query, vars, { onResponse })

const finalError = error || responseError
```

And if we set error like this https://github.com/relay-tools/relay-hooks/issues/176#issuecomment-865405533
We just continue to use `error` returned from useQuery.
Yes this is breaking change. Maybe we can make it optional with the flag?
```
const { data, error } = useQuery(query, vars, { partialSuccessError: true }) // I'm not sure about option name
```

**Comment by aleksandrlat** [comment]
`onResponse` also works and it would be great to have access to error even in this onResponse form.

**Comment by aleksandrlat** [comment]
Or maybe we can add `partialError` to useQuery result?
Something like this:
```
const { data, error, partialError } = useQuery(query, vars)
```

**Comment by aleksandrlat** [comment]
@morrys, @n1ru4l, @sibelius any thoughts on this?

**Comment by morrys** [comment]
solution 1: https://github.com/relay-tools/relay-hooks/pull/193#issuecomment-925301570
this is the solution I like least as the error value would have two different meanings

solution 2: https://github.com/relay-tools/relay-hooks/pull/193#issuecomment-925316914
This solution would not be bad if it were also implemented in relay, in relay-hooks I would like to deviate as little as possible from relay especially in the management of data that returns the hooks

solution 3: see https://github.com/relay-tools/relay-hooks/pull/193#issue-1004157902

**Comment by aleksandrlat** [comment]
Thank you @morrys!

> solution 1: https://github.com/relay-tools/relay-hooks/pull/193#issuecomment-925301570

The meaning is the same. It is still error. errorPolicy would align with other policies in relay: fetchPolicy, renderPolicy. 
I.e. we can include partial error optionally.
Let me try to propose this in relay repo!

> solution 2: https://github.com/relay-tools/relay-hooks/pull/193#issuecomment-925316914

When I thought about it I thought about usePagination hook when we return errorNext and so on.
relay-hooks are a bit different already. And if people want they can choose to use errorPolicy or partialError or not. 
I.e. they can decide to be 100% compatible with relay hooks. Do you think it is fine to let people decide?

solution 4 is always return partial error as `error`. Do you still consider this as option or not?

**Comment by aleksandrlat** [comment]
Or maybe even new hook? 😃 
```
const { data, error } = useQueryWithPartialErrors(query, vars)
```

@morrys if you are leaning towards onResponse it is also fine with me.

**Comment by aleksandrlat** [comment]
@morrys By the way apollo has errorPolicy https://www.apollographql.com/docs/react/data/error-handling/#graphql-error-policies

**Comment by morrys** [comment]
Hi @aleksandrlat,
I haven't forgotten about you, just too busy.

I understand that this solution is not the optimal one, I try to add some reflections.

 * [apollo error policies](https://www.apollographql.com/docs/react/data/error-handling/#graphql-error-policies)
   * none: If the response includes GraphQL errors, they are returned on error.graphQLErrors and the response data is set to undefined even if the server returns data in its response. This means network errors and GraphQL errors result in a similar response shape. This is the default error policy (**needs changes in relay-runtime**)
   * ignore: graphQLErrors are ignored (error.graphQLErrors is not populated), and any returned data is cached and rendered as if no errors occurred. (**relay default**)
   * all: Both data and error.graphQLErrors are populated, enabling you to render both partial results and error information (**this can be implemented in relay-hooks**)

relay core team seems to be decided on current relay error handling https://github.com/facebook/relay/issues/3621#issuecomment-958641003 and your proposal has not received a response at the moment https://github.com/facebook / relay/issues/3606

**Pull request merged**
