### PR TITLE
Fix typing issue #92 #93

### PR DESCRIPTION
**Pull request by morrys**
@earksiinni, 
here the PR that fixes the wrong typing you found

#93 fix connection config typing
#92 fix loadMore & refetchConnection arguments typing

### CODE REVIEW

**Comment by n1ru4l** [comment]
@renanmav @morrys Any information on when a version that contains this change will get published to npm?

**Comment by morrys** [comment]
hi @n1ru4l, 
actually I was hoping to reach 300 stars before releasing it :)

But if you are available to verify that the new release solves the problem, I can release it now too.

**Comment by morrys** [comment]
hi @n1ru4l,
I have just released relay-hooks 3.5.1
https://github.com/relay-tools/relay-hooks/releases/tag/v3.5.1

let me know if it's all fine :)
thanks

**Comment by n1ru4l** [comment]
@morrys Everything fine 😊 Thank you so much!

**Pull request merged**
