### PR TITLE
Fix issue 115

### PR DESCRIPTION
**Pull request by morrys**
This PR is in draft to verify issue #115

### CODE REVIEW

**Comment by morrys** [comment]
With this commit https://github.com/relay-tools/relay-hooks/pull/116/commits/ce305c36e877b4fc8041c12c774fdf0f65a5bd6c I created the test case of issue 115 and in fact the error appears.

**Comment by morrys** [comment]
With this commit https://github.com/relay-tools/relay-hooks/pull/116/commits/4be49a4103d5e3a38880407d1c2d08a60bdf6713 I have implemented the resolution of the issue.

The previously created test case is now passed.

**Comment by morrys** [comment]
hi @epiqueras,
in this PR I think I have recreated the test case of your problem and its resolution.

Before I can officially release it I have to do some more in-depth tests :)

In the meantime, could you try this version and check that your problem is solved?

Thanks

**Comment by epiqueras** [comment]
Yes, this does the trick, thank you!

So the issue was that it was querying using a disposed of query fetcher?

**Comment by morrys** [comment]
The issue problem is caused by this check here:
https://github.com/relay-tools/relay-hooks/blob/master/src/QueryFetcher.ts#L132 which with the dispose alone is not enough to pass that check.

In fact, this change is the key to solving your problem:
https://github.com/relay-tools/relay-hooks/blob/4be49a4103d5e3a38880407d1c2d08a60bdf6713/src/loadQuery.ts#L24

Being a very delicate point I prefer to do other tests before releasing the final solution :)

**Comment by epiqueras** [comment]
https://github.com/relay-tools/relay-hooks/blob/d9d0942c137cab4ae71ec12da26a5603ae99a5c5/src/QueryFetcher.ts#L86

How does that pass if the query is different from the last?

I also get this error when I fetch:

Query A ✅ 
Query B ✅ 
Query A Again ❌

**Comment by morrys** [comment]
Is it possible to execute the project you linked to me in the issue so that I can test the error myself?

**Comment by morrys** [comment]
In short:
when the check is passed the queryFetcher retrieves and saves the query data according to the fetchPolicy and subscribes to its updates.

The dispose deletes data and subscriptions.

**Comment by epiqueras** [comment]
Yeah, but I don't understand how the check is not passed if the last query was different.

Here are the commands to run it:

Install:

`git clone https://github.com/Proof-Of-Humanity/proof-of-humanity-web.git && cd proof-of-humanity-web && npm install && npm run build:graph`

In parallel:

`npm run dev:relay`
`npm run dev`

Then visit `localhost:3000?network=kovan`.

**Comment by epiqueras** [comment]
Comment out `setTimeout(() => prefetch.getValue().retry(), 0)` and try clicking on a profile and then going back by clicking "Profiles" in the header.

**Comment by morrys** [comment]
@epiqueras I ran the application with the released version of relay-hooks.

How do I create the issue error?

**Comment by morrys** [comment]
@epiqueras well, now everything seems to work, since it's 2:00 am in Italy I could be wrong :D

**Comment by epiqueras** [comment]
Ah, so the issue was that the hook should not call `dispose` on the query fetcher when unmounting? That makes more sense.

**Comment by epiqueras** [comment]
When will this be included in a release?

**Comment by morrys** [comment]
I think in 7/10 days ... I am making other changes for better compatibility with react-relay-offline

**Pull request merged**
