### PR TITLE
Added Generic for QueryVariables in useRefetch

### PR DESCRIPTION
**Pull request by roman-khasimyanov**
extend useRefetch to use Generic by generated Query type
`
useRefetch<TKey extends ArrayKeyType, TOperationType extends OperationType>
`

### CODE REVIEW

**Comment by morrys** [comment]
Hi @roman-khasimyanov ,
meanwhile, thank you for your contribution :)

At the moment I can't test but it seems a good change :)

Could you check if this change is also necessary in useRefetchable and usePagination?

Thank you

**Comment by roman-khasimyanov** [comment]
Hi @morrys, sure)

**Comment by morrys** [comment]
Hi @roman-khasimyanov,
thanks for adjusting the other hooks too :)

As soon as possible I will do my checks in order to release it for mid-March :)

**Comment by morrys** [comment]
Hi @roman-khasimyanov,
soon I hope to release version 3.2.0 with all accepted PR.

Thanks

**Pull request merged**
